In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn=sqlite3.connect('chinook.db')
cursor=conn.cursor()

In [ ]:
cursor.execute("""SELECT name FROM sqlite_master WHERE type='table';""")
tables=cursor.fetchall()
tables

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',)]

REVENUE ANALYSIS

In [ ]:
#What country generates the most revenue?

In [ ]:
df=pd.read_sql_query("""SELECT BillingCountry AS Countries, SUM(Total) AS Total_Revenue FROM invoices GROUP BY Countries ORDER BY Total_revenue DESC LIMIT 1;""",conn)
df

  Countries  Total_Revenue
0       USA         523.06

In [ ]:
#What city generates the most revenue?
df=pd.read_sql_query("""SELECT BillingCity AS City, SUM(Total) AS Total_Revenue FROM invoices GROUP BY City ORDER BY Total_revenue DESC LIMIT 1;""",conn)
df

     City  Total_Revenue
0  Prague          90.24

In [ ]:
#What is the average invoice value per country
df=pd.read_sql_query("""SELECT BillingCountry AS Country, AVG(Total)AS Average_Invoice_per_country  FROM invoices GROUP BY Country ORDER BY Average_Invoice_per_country DESC;""",conn)
df

           Country  Average_Invoice_per_country
0            Chile                     6.660000
1          Ireland                     6.517143
2          Hungary                     6.517143
3   Czech Republic                     6.445714
4          Austria                     6.088571
5          Finland                     5.945714
6      Netherlands                     5.802857
7            India                     5.789231
8              USA                     5.747912
9           Norway                     5.660000
10         Germany                     5.588571
11          France                     5.574286
12          Sweden                     5.517143
13        Portugal                     5.517143
14          Brazil                     5.431429
15          Canada                     5.427857
16          Poland                     5.374286
17           Italy                     5.374286
18         Denmark                     5.374286
19       Australia                     5.374286
20       Argentina                     5.374286
21  United Kingdom                     5.374286
22           Spain                     5.374286
23         Belgium                     5.374286

In [ ]:
#Which year had the Highest revenue?
df=pd.read_sql_query("""SELECT strftime('%Y',InvoiceDate) AS YEAR, SUM(Total)AS  Revenue  FROM invoices GROUP BY YEAR  ORDER BY Revenue DESC LIMIT 1 ;""",conn)
df

   YEAR  Revenue
0  2010   481.45

In [ ]:
#What are the Top 5 Revenue generting countries?
df=pd.read_sql_query("""SELECT BillingCountry AS Country, SUM(Total) AS Total_Revenue FROM invoices GROUP BY Country ORDER BY Total_Revenue DESC LIMIT 5;""",conn)
df

   Country  Total_Revenue
0      USA         523.06
1   Canada         303.96
2   France         195.10
3   Brazil         190.10
4  Germany         156.48

CUSTOMER BEHAVIOUR

In [ ]:
#Who are the TOP 10 Customers by Total Spending?
df=pd.read_sql_query("""SELECT C.FirstName AS First_Name, C.LastName AS Last_Name, SUM(I.Total) AS Total  FROM customers AS C JOIN invoices AS I ON C.CustomerId= I.CustomerId GROUP BY First_Name, Last_Name  ORDER BY Total DESC LIMIT 10;""",conn)
df

  First_Name   Last_Name  Total
0     Helena        Holý  49.62
1    Richard  Cunningham  47.62
2       Luis       Rojas  46.62
3       Hugh    O'Reilly  45.62
4   Ladislav      Kovács  45.62
5      Julia     Barnett  43.62
6      Frank     Ralston  43.62
7       Fynn  Zimmermann  43.62
8     Astrid      Gruber  42.62
9     Victor     Stevens  42.62

In [ ]:
#Which countries have the most customers?
df=pd.read_sql_query("""SELECT Country, COUNT(CustomerId) AS Number_of_customers FROM customers GROUP BY Country ORDER BY Number_of_customers DESC;""",conn)
df

           Country  Number_of_customers
0              USA                   13
1           Canada                    8
2           France                    5
3           Brazil                    5
4          Germany                    4
5   United Kingdom                    3
6         Portugal                    2
7            India                    2
8   Czech Republic                    2
9           Sweden                    1
10           Spain                    1
11          Poland                    1
12          Norway                    1
13     Netherlands                    1
14           Italy                    1
15         Ireland                    1
16         Hungary                    1
17         Finland                    1
18         Denmark                    1
19           Chile                    1
20         Belgium                    1
21         Austria                    1
22       Australia                    1
23       Argentina                    1

In [ ]:
#Do customers from some countries spend more than others?
df=pd.read_sql_query("""SELECT  C.Country AS Country, C.FirstName AS First_Name, C.LastName AS Last_Name, SUM(I.Total) AS Amount_Spent FROM customers AS C JOIN Invoices AS I ON C.CustomerId=I.CustomerId GROUP BY Country, First_Name, Last_Name ORDER BY Amount_Spent  DESC LIMIT 10;""",conn)
df

          Country First_Name   Last_Name  Amount_Spent
0  Czech Republic     Helena        Holý         49.62
1             USA    Richard  Cunningham         47.62
2           Chile       Luis       Rojas         46.62
3         Hungary   Ladislav      Kovács         45.62
4         Ireland       Hugh    O'Reilly         45.62
5             USA      Julia     Barnett         43.62
6         Germany       Fynn  Zimmermann         43.62
7             USA      Frank     Ralston         43.62
8         Austria     Astrid      Gruber         42.62
9             USA     Victor     Stevens         42.62

In [ ]:
#What is the average amount spent by the customer?
df=pd.read_sql_query("""SELECT C.FirstName AS First_Name, C.LastName AS Last_Name, AVG(I.Total) AS Amount_Spent FROM customers AS C JOIN Invoices AS I ON C.CustomerId=I.CustomerId  GROUP BY First_Name, Last_Name ORDER BY Amount_Spent  DESC LIMIT 10;""",conn)
df

  First_Name   Last_Name  Amount_Spent
0     Helena        Holý      7.088571
1    Richard  Cunningham      6.802857
2       Luis       Rojas      6.660000
3       Hugh    O'Reilly      6.517143
4   Ladislav      Kovács      6.517143
5      Julia     Barnett      6.231429
6      Frank     Ralston      6.231429
7       Fynn  Zimmermann      6.231429
8       Puja  Srivastava      6.106667
9     Astrid      Gruber      6.088571

PRODUCTS AND MUSIC TREND

In [ ]:
#Which Music genre sells the most?
df=pd.read_sql_query("""SELECT G.Name, COUNT(I.TrackId) AS TOTAL FROM invoice_items AS I JOIN Tracks AS T ON I.TrackId=T.TrackId JOIN genres AS G ON T.TrackId=G.GenreId GROUP BY G.Name ORDER BY TOTAL DESC;""",conn)
df

                  Name  TOTAL
0     Sci Fi & Fantasy      2
1               Reggae      2
2                  Pop      2
3                 Jazz      2
4                World      1
5             TV Shows      1
6           Soundtrack      1
7        Rock And Roll      1
8                 Rock      1
9             R&B/Soul      1
10               Opera      1
11               Metal      1
12         Heavy Metal      1
13   Electronica/Dance      1
14      Easy Listening      1
15               Drama      1
16           Classical      1
17               Blues      1
18  Alternative & Punk      1

In [ ]:
#Who are the Top selling Artists?
df=pd.read_sql_query("""SELECT AR.Name AS Artists, COUNT(I.TrackId) AS Total_Revenue FROM Invoice_items I JOIN Tracks T ON I.TrackId=T.TrackId  JOIN Albums A ON T.AlbumId= A.AlbumId JOIN artists AR ON A.ArtistId=AR.ArtistId GROUP BY Artists ORDER BY Total_Revenue LIMIT 10;""",conn)
df

                                             Artists  Total_Revenue
0  Academy of St. Martin in the Fields & Sir Nevi...              1
1  Academy of St. Martin in the Fields, John Birc...              1
2                     Adrian Leaper & Doreen de Feis              1
3           Antal Doráti & London Symphony Orchestra              1
4             Berliner Philharmoniker & Hans Rosbaud              1
5                                           Calexico              1
6                                     Dread Zeppelin              1
7              Edo de Waart & San Francisco Symphony              1
8  Emanuel Ax, Eugene Ormandy & Philadelphia Orch...              1
9                   English Concert & Trevor Pinnock              1

In [ ]:
#What is the Top selling Track?
df=pd.read_sql_query("""SELECT T.Name AS Tracks, COUNT(I.TrackId) AS Top_selling_Track FROM invoice_items AS I JOIN Tracks AS T ON I.TrackId=T.TrackId GROUP BY Tracks ORDER BY Top_selling_Track DESC LIMIT 1;""",conn)
df

        Tracks  Top_selling_Track
0  The Trooper                  5

In [ ]:
#Which genre generates the most revenue?
df=pd.read_sql_query("""SELECT G.Name AS Genre, SUM(I.UnitPrice*Quantity) AS Revenue  FROM invoice_items AS I JOIN Tracks AS T ON I.invoiceId=T.TrackId JOIN Genres AS G ON T.GenreId=G.GenreId GROUP BY Genre ORDER BY Revenue DESC  LIMIT 1;""",conn)
df

   Genre  Revenue
0  Latin   676.41

EMPLOYEE PERFORMANCE

In [ ]:
#which employee supports the highest spending customer?
df=pd.read_sql_query("""SELECT E.FirstName AS EMPLOYEE_FIRST_NAME, E.LastName AS EMPLOYEE_LAST_NAME, C.FirstName AS CUSTOMER_FIRST_NAME,C.LastName AS CUSTOMER_LAST_NAME, SUM(I.Total) AS AMOUNT_SPENT  FROM employees AS E JOIN customers AS C ON E.EmployeeId= C.SupportRepId JOIN Invoices AS I ON C.CustomerId=I.CustomerId GROUP BY EMPLOYEE_FIRST_NAME, EMPLOYEE_LAST_NAME, CUSTOMER_FIRST_NAME, CUSTOMER_LAST_NAME ORDER BY AMOUNT_SPENT DESC LIMIT 11;""",conn)
df

,EMPLOYEE_FIRST_NAME,EMPLOYEE_LAST_NAME,CUSTOMER_FIRST_NAME,CUSTOMER_LAST_NAME,AMOUNT_SPENT
0,Steve,Johnson,Helena,Holý,49.62
1,Margaret,Park,Richard,Cunningham,47.62
2,Steve,Johnson,Luis,Rojas,46.62
3,Jane,Peacock,Hugh,O'Reilly,45.62
4,Jane,Peacock,Ladislav,Kovács,45.62
5,Steve,Johnson,Julia,Barnett,43.62
6,Jane,Peacock,Frank,Ralston,43.62
7,Jane,Peacock,Fynn,Zimmermann,43.62
8,Steve,Johnson,Astrid,Gruber,42.62
9,Steve,Johnson,Victor,Stevens,42.62
10,Jane,Peacock,Terhi,Hämäläinen,41.62

In [ ]:
#Which employee  generates the most revenue?
df=pd.read_sql_query("""SELECT E.FirstName AS First_Name, E.LastName AS Last_Name, SUM(I.Total) AS Total_Revenue FROM employees AS E JOIN customers C ON E.EmployeeId=C.SupportRepId  JOIN Invoices I ON C.CustomerId=I.CustomerId GROUP BY First_Name, Last_Name ORDER BY Total_Revenue DESC LIMIT 1;""",conn)
df

  First_Name Last_Name  Total_Revenue
0       Jane   Peacock         833.04

In [ ]:
conn.close()